import { RBTree } from "../src/rbtree";

import * as mocha from "mocha";
import * as chai from "chai";

const expect = chai.expect;

describe("creation", () => {
  it("empty", () => {
    const T = new RBTree<number>();
    expect(T.root).to.eql(null);
  });
  it("singleton", () => {
    const T = new RBTree<number>();
    const U = T.insert("a", 1);
    expect(T.root).to.eql(null);
    expect(U.root).to.eql({ kind: "black", key: "a", value: 1, lhs: null, rhs: null });
  });
  it("a few items", () => {
    const items: [string, number][] = [
      ["a", 1],
      ["b", 2],
      ["c", 3],
      ["d", 4],
      ["e", 5],
    ];
    const T = new RBTree<number>();
    const U = T.insertMany(items);
    expect(T.root).to.eql(null);
    expect(U.root).to.eql({
      kind: "black",
      key: "b",
      value: 2,
      lhs: { kind: "black", key: "a", value: 1, lhs: null, rhs: null },
      rhs: {
        kind: "red",
        key: "d",
        value: 4,
        lhs: { kind: "black", key: "c", value: 3, lhs: null, rhs: null },
        rhs: { kind: "black", key: "e", value: 5, lhs: null, rhs: null },
      },
    });
  });
  describe("lots of items", () => {
    const names: string[] = [
      "Eucalyptus × alpina",
      "Eucalyptus × balanites",
      "Eucalyptus × balanopelex",
      "Eucalyptus × beyeri",
      "Eucalyptus × brachyphylla",
      "Eucalyptus × chrysantha",
      "Eucalyptus × conjuncta",
      "Eucalyptus × kalangadooensis",
      "Eucalyptus × lamprocalyx",
      "Eucalyptus × laseronii",
      "Eucalyptus × macmahonii",
      "Eucalyptus × missilis",
      "Eucalyptus × nepeanensis",
      "Eucalyptus × nowraensis",
      "Eucalyptus × phylacis",
      "Eucalyptus × stoataptera",
      "Eucalyptus × tokwa",
      "Eucalyptus × urnularis",
      "Eucalyptus abdita",
      "Eucalyptus absita",
      "Eucalyptus acaciiformis",
      "Eucalyptus accedens",
      "Eucalyptus acies",
      "Eucalyptus acmenoides",
      "Eucalyptus acroleuca",
      "Eucalyptus adesmophloia",
      "Eucalyptus aequioperta",
      "Eucalyptus agglomerata",
      "Eucalyptus aggregata",
      "Eucalyptus alaticaulis",
      "Eucalyptus alatissima",
      "Eucalyptus alba ex",
      "Eucalyptus alba var. australasica",
      "Eucalyptus albens",
      "Eucalyptus albida",
      "Eucalyptus albopurpurea",
      "Eucalyptus alipes",
      "Eucalyptus alligatrix",
      "Eucalyptus alligatrix subsp. alligatrix",
      "Eucalyptus alligatrix subsp. limaensis",
      "Eucalyptus alligatrix subsp. miscella",
      "Eucalyptus ammophila",
      "Eucalyptus amplifolia",
      "Eucalyptus amplifolia subsp. amplifolia",
      "Eucalyptus amplifolia subsp. sessiliflora",
      "Eucalyptus amygdalina",
      "Eucalyptus ancophila",
      "Eucalyptus andrewsii",
      "Eucalyptus angophoroides",
      "Eucalyptus angularis",
      "Eucalyptus angulosa",
      "Eucalyptus angustissima",
      "Eucalyptus annettae",
      "Eucalyptus annulata",
      "Eucalyptus annuliformis",
      "Eucalyptus apiculata",
      "Eucalyptus apodophylla",
      "Eucalyptus apothalassica",
      "Eucalyptus approximans",
      "Eucalyptus aquatica",
      "Eucalyptus aquilina",
      "Eucalyptus arachnaea",
      "Eucalyptus arachnaea subsp. arachnaea",
      "Eucalyptus arachnaea subsp. arrecta",
      "Eucalyptus arborella",
      "Eucalyptus arcana",
      "Eucalyptus archeri",
      "Eucalyptus arenacea",
      "Eucalyptus arenicola",
      "Eucalyptus argillacea",
      "Eucalyptus argophloia",
      "Eucalyptus argutifolia",
      "Eucalyptus aridimontana",
      "Eucalyptus armillata",
      "Eucalyptus aromaphloia",
      "Eucalyptus articulata",
      "Eucalyptus aspersa",
      "Eucalyptus aspratilis",
      "Eucalyptus assimilans",
      "Eucalyptus astringens",
      "Eucalyptus astringens subsp. astringens",
      "Eucalyptus astringens subsp. redacta",
      "Eucalyptus atrata",
      "Eucalyptus aurifodina",
      "Eucalyptus badjensis",
      "Eucalyptus baeuerlenii",
      "Eucalyptus baileyana",
      "Eucalyptus baiophylla",
      "Eucalyptus bakeri",
      "Eucalyptus balladoniensis",
      "Eucalyptus balladoniensis subsp. balladoniensis",
      "Eucalyptus balladoniensis subsp. sedens",
      "Eucalyptus bancroftii",
      "Eucalyptus banksii",
      "Eucalyptus barberi",
      "Eucalyptus baudiniana",
      "Eucalyptus baueriana",
      "Eucalyptus baueriana subsp. baueriana",
      "Eucalyptus baueriana subsp. deddickensis",
      "Eucalyptus baueriana subsp. thalassina",
      "Eucalyptus baxteri",
      "Eucalyptus beaniana",
      "Eucalyptus beardiana",
      "Eucalyptus behriana",
      "Eucalyptus bensonii",
      "Eucalyptus benthamii",
      "Eucalyptus beyeriana",
      "Eucalyptus bigalerita",
      "Eucalyptus blakelyi",
      "Eucalyptus blaxellii",
      "Eucalyptus blaxlandii",
      "Eucalyptus boliviana",
      "Eucalyptus bosistoana",
      "Eucalyptus botryoides",
      "Eucalyptus brachyandra",
      "Eucalyptus brachycalyx",
      "Eucalyptus brandiana",
      "Eucalyptus brassiana",
      "Eucalyptus brevifolia",
      "Eucalyptus brevipes",
      "Eucalyptus brevistylis",
      "Eucalyptus bridgesiana",
      "Eucalyptus brockwayi",
      "Eucalyptus brookeriana",
      "Eucalyptus broviniensis",
      "Eucalyptus brownii",
      "Eucalyptus bunyip",
      "Eucalyptus buprestium",
      "Eucalyptus burdettiana",
      "Eucalyptus burgessiana",
      "Eucalyptus burracoppinensis",
      "Eucalyptus cadens",
      "Eucalyptus caesia",
      "Eucalyptus cajuputea",
      "Eucalyptus calcareana",
      "Eucalyptus calcicola",
      "Eucalyptus calcicola subsp. calcicola",
      "Eucalyptus calcicola subsp. unita",
      "Eucalyptus caleyi",
      "Eucalyptus caleyi subsp. caleyi",
      "Eucalyptus caleyi subsp. ovendenii",
      "Eucalyptus caliginosa",
      "Eucalyptus calycogona",
      "Eucalyptus calycogona subsp. calycogona",
      "Eucalyptus calycogona subsp. miraculum",
      "Eucalyptus calycogona subsp. spaffordii",
      "Eucalyptus calycogona subsp. trachybasis",
      "Eucalyptus calyerup",
      "Eucalyptus camaldulensis",
      "Eucalyptus camaldulensis subsp. acuta",
      "Eucalyptus camaldulensis subsp. arida",
      "Eucalyptus camaldulensis subsp. minima",
      "Eucalyptus camaldulensis subsp. obtusa",
      "Eucalyptus camaldulensis subsp. refulgens",
      "Eucalyptus camaldulensis subsp. simulata",
      "Eucalyptus cambageana",
      "Eucalyptus cameronii",
      "Eucalyptus camfieldii",
      "Eucalyptus campanulata",
      "Eucalyptus campaspe",
      "Eucalyptus camphora",
      "Eucalyptus camphora subsp. camphora",
      "Eucalyptus camphora subsp. humeana",
      "Eucalyptus canaliculata",
      "Eucalyptus canescens",
      "Eucalyptus canescens subsp. beadellii",
      "Eucalyptus canescens subsp. canescens",
      "Eucalyptus canobolensis",
      "Eucalyptus capillosa",
      "Eucalyptus capillosa subsp. capillosa",
      "Eucalyptus capillosa subsp. polyclada",
      "Eucalyptus capitanea",
      "Eucalyptus capitellata",
      "Eucalyptus captiosa",
      "Eucalyptus carnea",
      "Eucalyptus carnei",
      "Eucalyptus carolaniae",
      "Eucalyptus castrensis",
      "Eucalyptus celastroides",
      "Eucalyptus celastroides subsp. celastroides",
      "Eucalyptus celastroides subsp. virella",
      "Eucalyptus cephalocarpa",
      "Eucalyptus ceracea",
      "Eucalyptus cerasiformis",
      "Eucalyptus ceratocorys",
      "Eucalyptus cernua",
      "Eucalyptus chapmaniana",
      "Eucalyptus chartaboma",
      "Eucalyptus chloroclada",
      "Eucalyptus chlorophylla",
      "Eucalyptus cinerea",
      "Eucalyptus cinerea subsp. cinerea",
      "Eucalyptus cinerea subsp. triplex",
      "Eucalyptus cladocalyx",
      "Eucalyptus cladocalyx subsp. crassaD.Nicholle",
      "Eucalyptus cladocalyx subsp. petilaD.Nicholle",
      "Eucalyptus clelandiorum",
      "Eucalyptus clivicola",
      "Eucalyptus cloeziana",
      "Eucalyptus cneorifolia",
      "Eucalyptus coccifera",
      "Eucalyptus codonocarpa",
      "Eucalyptus comitae-vallis",
      "Eucalyptus concinna",
      "Eucalyptus conferruminata",
      "Eucalyptus conferruminata subsp. conferruminata",
      "Eucalyptus conferruminata subsp. recherche",
      "Eucalyptus conferta",
      "Eucalyptus confluens",
      "Eucalyptus conglobata",
      "Eucalyptus conglobata subsp. conglobata",
      "Eucalyptus conglobata subsp. perata",
      "Eucalyptus conglomerata",
      "Eucalyptus conica",
      "Eucalyptus consideniana",
      "Eucalyptus conspicua",
      "Eucalyptus conveniens",
      "Eucalyptus coolabah",
      "Eucalyptus cooperiana",
      "Eucalyptus copulans",
      "Eucalyptus cordata",
      "Eucalyptus cordata subsp. cordata",
      "Eucalyptus cordata subsp. quadrangulosa",
      "Eucalyptus cornuta",
      "Eucalyptus coronata",
      "Eucalyptus corrugata",
      "Eucalyptus corticosa",
      "Eucalyptus corynodes",
      "Eucalyptus cosmophylla",
      "Eucalyptus costuligera",
      "Eucalyptus crebra",
      "Eucalyptus crenulata",
      "Eucalyptus creta",
      "Eucalyptus cretata",
      "Eucalyptus crispata",
      "Eucalyptus croajingolensis",
      "Eucalyptus crucis",
      "Eucalyptus crucis subsp. crucis – silver mallee",
      "Eucalyptus crucis subsp. lanceolata",
      "Eucalyptus crucis subsp. praecipua",
      "Eucalyptus cullenii",
      "Eucalyptus cunninghamii",
      "Eucalyptus cuprea",
      "Eucalyptus cupularis",
      "Eucalyptus curtisii",
      "Eucalyptus cuspidata",
      "Eucalyptus cyanophylla",
      "Eucalyptus cyclostoma",
      "Eucalyptus cylindriflora",
      "Eucalyptus cylindrocarpa",
      "Eucalyptus cypellocarpa",
      "Eucalyptus dalrympleana",
      "Eucalyptus dalrympleana subsp. dalrympleana",
      "Eucalyptus dalrympleana subsp. heptantha",
      "Eucalyptus dawsonii",
      "Eucalyptus dealbata",
      "Eucalyptus deanei",
      "Eucalyptus decipiens",
      "Eucalyptus decolor",
      "Eucalyptus decorticans",
      "Eucalyptus decurva",
      "Eucalyptus deflexa",
      "Eucalyptus deglupta",
      "Eucalyptus delegatensis",
      "Eucalyptus delegatensis subsp. delegatensis",
      "Eucalyptus delegatensis subsp. tasmaniensis",
      "Eucalyptus delicata",
      "Eucalyptus dendromorpha",
      "Eucalyptus densa",
      "Eucalyptus densa subsp. densa",
      "Eucalyptus densa subsp. improcera",
      "Eucalyptus denticulata",
      "Eucalyptus depauperata",
      "Eucalyptus desmondensis",
      "Eucalyptus deuaensis",
      "Eucalyptus dielsii",
      "Eucalyptus diminuta",
      "Eucalyptus diptera",
      "Eucalyptus discreta",
      "Eucalyptus dissimulata",
      "Eucalyptus distans",
      "Eucalyptus distuberosa",
      "Eucalyptus distuberosa subsp. aerata",
      "Eucalyptus distuberosa subsp. distuberosa",
      "Eucalyptus diversicolor",
      "Eucalyptus diversifolia",
      "Eucalyptus diversifolia subsp. diversifolia – soap mallee, coastal white mallee, coast gum",
      "Eucalyptus diversifolia subsp. hesperia",
      "Eucalyptus dives",
      "Eucalyptus dolichocera",
      "Eucalyptus dolichorhyncha",
      "Eucalyptus dolorosa",
      "Eucalyptus doratoxylon",
      "Eucalyptus dorrigoensis",
      "Eucalyptus drummondii",
      "Eucalyptus dumosa",
      "Eucalyptus dundasii",
      "Eucalyptus dunnii",
      "Eucalyptus dura",
      "Eucalyptus dwyeri",
      "Eucalyptus ebbanoensis",
      "Eucalyptus ebbanoensis subsp. ebbanoensis",
      "Eucalyptus ebbanoensis subsp. glauciramula",
      "Eucalyptus ebbanoensis subsp. photina",
      "Eucalyptus ecostata",
      "Eucalyptus educta",
      "Eucalyptus effusa",
      "Eucalyptus effusa subsp. effusa",
      "Eucalyptus effusa subsp. exsul",
      "Eucalyptus elaeophloia",
      "Eucalyptus elata",
      "Eucalyptus elegans",
      "Eucalyptus elliptica",
      "Eucalyptus erectifolia",
      "Eucalyptus eremicola",
      "Eucalyptus eremicola subsp. eremicola",
      "Eucalyptus eremicola subsp. peeneri",
      "Eucalyptus eremophila",
      "Eucalyptus eremophila subsp. pterocarpa",
      "Eucalyptus erosa",
      "Eucalyptus erythrocorys",
      "Eucalyptus erythronema",
      "Eucalyptus erythronema subsp. inornata",
      "Eucalyptus eudesmioides",
      "Eucalyptus eugenioides",
      "Eucalyptus ewartiana",
      "Eucalyptus exigua",
      "Eucalyptus exilipes",
      "Eucalyptus exilis",
      "Eucalyptus expressa",
      "Eucalyptus exserta",
      "Eucalyptus extensa",
      "Eucalyptus extrica",
      "Eucalyptus falcata",
      "Eucalyptus falciformis",
      "Eucalyptus famelica",
      "Eucalyptus farinosa",
      "Eucalyptus fasciculosa",
      "Eucalyptus fastigata",
      "Eucalyptus fibrosa",
      "Eucalyptus fibrosa subsp. fibrosa",
      "Eucalyptus fibrosa subsp. nubila",
      "Eucalyptus filiformis",
      "Eucalyptus fitzgeraldii",
      "Eucalyptus flavida",
      "Eucalyptus flindersii",
      "Eucalyptus flocktoniae",
      "Eucalyptus flocktoniae subsp. flocktoniae",
      "Eucalyptus flocktoniae subsp. hebes",
      "Eucalyptus foecunda",
      "Eucalyptus foliosa",
      "Eucalyptus formanii",
      "Eucalyptus forresterae",
      "Eucalyptus forrestiana",
      "Eucalyptus fracta",
      "Eucalyptus fraseri",
      "Eucalyptus fraseri subsp. fraseri",
      "Eucalyptus fraseri subsp. melanobasis",
      "Eucalyptus fraxinoides",
      "Eucalyptus frenchiana",
      "Eucalyptus froggattii",
      "Eucalyptus fruticosa",
      "Eucalyptus fulgens",
      "Eucalyptus fusiformis",
      "Eucalyptus gamophylla",
      "Eucalyptus gardneri",
      "Eucalyptus gardneri subsp. gardneri",
      "Eucalyptus gardneri subsp. ravensthorpensis",
      "Eucalyptus georgei",
      "Eucalyptus georgei subsp. fulgida",
      "Eucalyptus georgei subsp. georgei",
      "Eucalyptus gigantangion",
      "Eucalyptus gillenii",
      "Eucalyptus gillii",
      "Eucalyptus gittinsii",
      "Eucalyptus gittinsii subsp. gittinsii",
      "Eucalyptus gittinsii subsp. illucida",
      "Eucalyptus glaucescens",
      "Eucalyptus glaucina",
      "Eucalyptus globoidea",
      "Eucalyptus globulus",
      "Eucalyptus globulus subsp. bicostata",
      "Eucalyptus globulus subsp. maidenii",
      "Eucalyptus globulus subsp. pseudoglobulus",
      "Eucalyptus glomericassis",
      "Eucalyptus glomerosa",
      "Eucalyptus gomphocephala",
      "Eucalyptus gongylocarpa",
      "Eucalyptus goniantha",
      "Eucalyptus goniantha subsp. goniantha",
      "Eucalyptus goniantha subsp. kynoura",
      "Eucalyptus goniocalyx",
      "Eucalyptus goniocalyx subsp. exposa",
      "Eucalyptus goniocalyx subsp. fallax",
      "Eucalyptus goniocalyx subsp. goniocalyx",
      "Eucalyptus goniocalyx subsp. laxa",
      "Eucalyptus goniocalyx subsp. viridissima",
      "Eucalyptus goniocarpa",
      "Eucalyptus gracilis",
      "Eucalyptus grandis",
      "Eucalyptus granitica",
      "Eucalyptus gregoryensis",
      "Eucalyptus gregsoniana",
      "Eucalyptus griffithsii",
      "Eucalyptus grisea",
      "Eucalyptus grossa",
      "Eucalyptus guilfoylei",
      "Eucalyptus gunnii",
      "Eucalyptus gunnii subsp. divaricata",
      "Eucalyptus gunnii subsp. gunnii",
      "Eucalyptus gypsophila",
      "Eucalyptus haemastoma",
      "Eucalyptus hallii",
      "Eucalyptus halophila",
      "Eucalyptus hawkeri",
      "Eucalyptus hebetifolia",
      "Eucalyptus helidonica",
      "Eucalyptus herbertiana",
      "Eucalyptus histophylla",
      "Eucalyptus horistes",
      "Eucalyptus houseana",
      "Eucalyptus howittiana",
      "Eucalyptus hypolaena",
      "Eucalyptus hypostomatica",
      "Eucalyptus ignorabilis",
      "Eucalyptus imitans",
      "Eucalyptus imlayensis",
      "Eucalyptus impensa",
      "Eucalyptus incerata",
      "Eucalyptus incrassata",
      "Eucalyptus indurata",
      "Eucalyptus infera",
      "Eucalyptus infracorticata",
      "Eucalyptus insularis",
      "Eucalyptus insularis subsp. continentalis",
      "Eucalyptus insularis subsp. insularis",
      "Eucalyptus interstans",
      "Eucalyptus intertexta",
      "Eucalyptus jacksonii",
      "Eucalyptus jensenii",
      "Eucalyptus jimberlanica",
      "Eucalyptus johnsoniana",
      "Eucalyptus johnstonii",
      "Eucalyptus jucunda",
      "Eucalyptus jutsonii",
      "Eucalyptus jutsonii subsp. jutsonii",
      "Eucalyptus jutsonii subsp. kobela",
      "Eucalyptus kabiana",
      "Eucalyptus kartzoffiana",
      "Eucalyptus kenneallyi",
      "Eucalyptus kessellii",
      "Eucalyptus kessellii subsp. eugnosta",
      "Eucalyptus kessellii subsp. kessellii",
      "Eucalyptus kingsmillii",
      "Eucalyptus kingsmillii subsp. kingsmillii",
      "Eucalyptus kitsoniana",
      "Eucalyptus kochii",
      "Eucalyptus kochii subsp. amaryssia",
      "Eucalyptus kochii subsp. borealis",
      "Eucalyptus kochii subsp. kochii",
      "Eucalyptus kochii subsp. plenissima",
      "Eucalyptus kochii subsp. yellowdinensis",
      "Eucalyptus kondininensis",
      "Eucalyptus koolpinensis",
      "Eucalyptus kruseana",
      "Eucalyptus kumarlensis",
      "Eucalyptus kybeanensis",
      "Eucalyptus lacrimans",
      "Eucalyptus laeliae",
      "Eucalyptus laevis",
      "Eucalyptus laevopinea",
      "Eucalyptus lane-poolei",
      "Eucalyptus langleyi",
      "Eucalyptus lansdowneana",
      "Eucalyptus largeana",
      "Eucalyptus largiflorens",
      "Eucalyptus latens",
      "Eucalyptus lateritica",
      "Eucalyptus latisinensis",
      "Eucalyptus lehmannii",
      "Eucalyptus lehmannii subsp. lehmannii",
      "Eucalyptus lehmannii subsp. parallela",
      "Eucalyptus leprophloia",
      "Eucalyptus leptocalyx",
      "Eucalyptus leptocalyx subsp. leptocalyx",
      "Eucalyptus leptocalyx subsp. petilipes",
      "Eucalyptus leptophleba",
      "Eucalyptus leptophylla",
      "Eucalyptus leptopoda",
      "Eucalyptus leptopoda subsp. arctata",
      "Eucalyptus leptopoda subsp. elevata",
      "Eucalyptus leptopoda subsp. leptopoda",
      "Eucalyptus leptopoda subsp. subluta",
      "Eucalyptus lesouefii",
      "Eucalyptus leucophloia",
      "Eucalyptus leucophloia subsp. euroa",
      "Eucalyptus leucophloia subsp. leucophloia",
      "Eucalyptus leucophylla",
      "Eucalyptus leucoxylon",
      "Eucalyptus leucoxylon subsp. bellarinensis",
      "Eucalyptus leucoxylon subsp. connata",
      "Eucalyptus leucoxylon subsp. leucoxylon",
      "Eucalyptus leucoxylon subsp. megalocarpa",
      "Eucalyptus leucoxylon subsp. pruinosa",
      "Eucalyptus leucoxylon subsp. stephaniae",
      "Eucalyptus leucoxylon var. pluriflora",
      "Eucalyptus ligulata",
      "Eucalyptus ligulata subsp. ligulata",
      "Eucalyptus ligulata subsp. stirlingica",
      "Eucalyptus ligustrina",
      "Eucalyptus limitaris",
      "Eucalyptus lirata",
      "Eucalyptus litoralis",
      "Eucalyptus litorea",
      "Eucalyptus livida",
      "Eucalyptus lockyeri",
      "Eucalyptus lockyeri subsp. exuta",
      "Eucalyptus lockyeri subsp. lockyeri",
      "Eucalyptus longicornis",
      "Eucalyptus longifolia",
      "Eucalyptus longirostrata",
      "Eucalyptus longissima",
      "Eucalyptus loxophleba",
      "Eucalyptus loxophleba subsp. gratiae",
      "Eucalyptus loxophleba subsp. lissophloia",
      "Eucalyptus loxophleba subsp. loxophleba",
      "Eucalyptus loxophleba subsp. supralaevis",
      "Eucalyptus lucasii",
      "Eucalyptus lucens",
      "Eucalyptus luculenta",
      "Eucalyptus luehmanniana",
      "Eucalyptus luteola",
      "Eucalyptus macarthurii",
      "Eucalyptus mackintii",
      "Eucalyptus macrandra",
      "Eucalyptus macrocarpa",
      "Eucalyptus macrocarpa subsp. elachantha",
      "Eucalyptus macrocarpa subsp. macrocarpa",
      "Eucalyptus macrorhyncha",
      "Eucalyptus macrorhyncha subsp. cannonii",
      "Eucalyptus macrorhyncha subsp. macrorhyncha",
      "Eucalyptus magnificata",
      "Eucalyptus major",
      "Eucalyptus malacoxylon",
      "Eucalyptus mannensis",
      "Eucalyptus mannensis subsp. mannensis",
      "Eucalyptus mannensis subsp. vespertina",
      "Eucalyptus mannifera",
      "Eucalyptus mannifera subsp. gullickii",
      "Eucalyptus mannifera subsp. mannifera",
      "Eucalyptus mannifera subsp. praecox",
      "Eucalyptus marginata",
      "Eucalyptus marginata subsp. marginata",
      "Eucalyptus marginata subsp. thalassica",
      "Eucalyptus mckieana",
      "Eucalyptus mcquoidii",
      "Eucalyptus mediocris",
      "Eucalyptus megacarpa",
      "Eucalyptus megacornuta",
      "Eucalyptus megasepala",
      "Eucalyptus melanoleuca",
      "Eucalyptus melanophitra",
      "Eucalyptus melanophloia",
      "Eucalyptus melanophloia subsp. melanophloia",
      "Eucalyptus melanophloia subsp. nana",
      "Eucalyptus melanoxylon",
      "Eucalyptus melliodora",
      "Eucalyptus merrickiae",
      "Eucalyptus michaeliana",
      "Eucalyptus micranthera",
      "Eucalyptus microcarpa",
      "Eucalyptus microcorys",
      "Eucalyptus microneura",
      "Eucalyptus microschema",
      "Eucalyptus microtheca",
      "Eucalyptus mimica",
      "Eucalyptus mimica subsp. continens",
      "Eucalyptus mimica subsp. mimica",
      "Eucalyptus miniata",
      "Eucalyptus minniritchi",
      "Eucalyptus misella",
      "Eucalyptus mitchelliana",
      "Eucalyptus moderata",
      "Eucalyptus moluccana",
      "Eucalyptus molyneuxii",
      "Eucalyptus mooreana",
      "Eucalyptus moorei",
      "Eucalyptus moorei subsp. moorei",
      "Eucalyptus moorei subsp.. serpentinicola",
      "Eucalyptus morrisbyi",
      "Eucalyptus morrisii",
      "Eucalyptus muelleriana",
      "Eucalyptus multicaulis",
      "Eucalyptus myriadena",
      "Eucalyptus myriadena subsp. myriadena",
      "Eucalyptus myriadena subsp. parviflora",
      "Eucalyptus nandewarica",
      "Eucalyptus nebulosa",
      "Eucalyptus neglecta",
      "Eucalyptus neutra",
      "Eucalyptus newbeyi",
      "Eucalyptus nicholii",
      "Eucalyptus nigrifunda",
      "Eucalyptus nitens",
      "Eucalyptus nitida",
      "Eucalyptus nobilis",
      "Eucalyptus normantonensis",
      "Eucalyptus nortonii",
      "Eucalyptus notabilis",
      "Eucalyptus notactites",
      "Eucalyptus nova-anglica",
      "Eucalyptus nudicaulis",
      "Eucalyptus nutans",
      "Eucalyptus obconica",
      "Eucalyptus obesa",
      "Eucalyptus obliqua",
      "Eucalyptus obtusiflora",
      "Eucalyptus obtusiflora subsp. cowcowensis",
      "Eucalyptus obtusiflora subsp. dongarraensis",
      "Eucalyptus obtusiflora subsp. obtusiflora",
      "Eucalyptus occidentalis",
      "Eucalyptus ochrophloia",
      "Eucalyptus odontocarpa",
      "Eucalyptus odorata",
      "Eucalyptus oldfieldii",
      "Eucalyptus oleosa",
      "Eucalyptus oleosa subsp. ampliata",
      "Eucalyptus oleosa subsp. corvina",
      "Eucalyptus oleosa subsp. cylindroidea",
      "Eucalyptus oleosa subsp. oleosa",
      "Eucalyptus olida",
      "Eucalyptus oligantha",
      "Eucalyptus oligantha subsp. modica",
      "Eucalyptus oligantha subsp. oligantha",
      "Eucalyptus olivina",
      "Eucalyptus olsenii",
      "Eucalyptus ophitica",
      "Eucalyptus opimiflora",
      "Eucalyptus optima",
      "Eucalyptus oraria",
      "Eucalyptus orbifolia",
      "Eucalyptus ordiana",
      "Eucalyptus oreades",
      "Eucalyptus orgadophila",
      "Eucalyptus ornans",
      "Eucalyptus ornata",
      "Eucalyptus orophila",
      "Eucalyptus orthostemon",
      "Eucalyptus ovata",
      "Eucalyptus ovata var. grandiflora",
      "Eucalyptus ovularis",
      "Eucalyptus oxymitra",
      "Eucalyptus pachycalyx",
      "Eucalyptus pachycalyx subsp. banyabba",
      "Eucalyptus pachycalyx subsp. pachycalyx",
      "Eucalyptus pachycalyx subsp. waajensis",
      "Eucalyptus pachyloma",
      "Eucalyptus pachyphylla",
      "Eucalyptus paedoglauca",
      "Eucalyptus paliformis",
      "Eucalyptus paludicola",
      "Eucalyptus panda",
      "Eucalyptus paniculata",
      "Eucalyptus pantoleuca",
      "Eucalyptus paralimnetica",
      "Eucalyptus parramattensis",
      "Eucalyptus parramattensis subsp. decadens",
      "Eucalyptus parramattensis subsp. parramattensis",
      "Eucalyptus parramattensis var. sphaerocalyx",
      "Eucalyptus parvula",
      "Eucalyptus patellaris",
      "Eucalyptus patens",
      "Eucalyptus pauciflora",
      "Eucalyptus pauciflora subsp. acerina",
      "Eucalyptus pauciflora subsp. debeuzevillei",
      "Eucalyptus pauciflora subsp. hedraia",
      "Eucalyptus pauciflora subsp. niphophila",
      "Eucalyptus pauciflora subsp. parvifructa",
      "Eucalyptus pauciflora var. × cylindrocarpa",
      "Eucalyptus pauciflora var. × densiflora",
      "Eucalyptus pauciflora var. × rusticata",
      "Eucalyptus pellita",
      "Eucalyptus pendens",
      "Eucalyptus peninsularis",
      "Eucalyptus perangusta",
      "Eucalyptus percostata",
      "Eucalyptus perriniana",
      "Eucalyptus persistens",
      "Eucalyptus petiolaris",
      "Eucalyptus petraea",
      "Eucalyptus petrensis",
      "Eucalyptus phaenophylla",
      "Eucalyptus phaenophylla subsp. interjacens",
      "Eucalyptus phenax",
      "Eucalyptus phenax subsp. compressa",
      "Eucalyptus phoenicea",
      "Eucalyptus phoenix",
      "Eucalyptus pilbarensis",
      "Eucalyptus pileata",
      "Eucalyptus pilularis",
      "Eucalyptus pimpiniana",
      "Eucalyptus piperita",
      "Eucalyptus placita",
      "Eucalyptus planchoniana",
      "Eucalyptus planipes",
      "Eucalyptus platycorys",
      "Eucalyptus platydisca",
      "Eucalyptus platyphylla",
      "Eucalyptus platypus",
      "Eucalyptus platypus subsp. congregata",
      "Eucalyptus pleurocarpa",
      "Eucalyptus pleurocorys",
      "Eucalyptus pluricaulis",
      "Eucalyptus pluricaulis subsp. porphyrea",
      "Eucalyptus polita",
      "Eucalyptus polyanthemos",
      "Eucalyptus polyanthemos subsp. longior",
      "Eucalyptus polyanthemos subsp. marginalis",
      "Eucalyptus polyanthemos subsp. vestita",
      "Eucalyptus polybractea",
      "Eucalyptus populnea",
      "Eucalyptus porosa",
      "Eucalyptus praetermissa",
      "Eucalyptus prava",
      "Eucalyptus preissiana",
      "Eucalyptus preissiana subsp. lobata",
      "Eucalyptus prolixa",
      "Eucalyptus prominens",
      "Eucalyptus propinqua",
      "Eucalyptus protensa",
      "Eucalyptus provecta",
      "Eucalyptus proxima",
      "Eucalyptus pruiniramis",
      "Eucalyptus pruinosa",
      "Eucalyptus pruinosa subsp. pruinosa",
      "Eucalyptus pruinosa subsp. tenuata",
      "Eucalyptus psammitica",
      "Eucalyptus pterocarpa",
      "Eucalyptus pulchella",
      "Eucalyptus pulverulenta",
      "Eucalyptus pumila",
      "Eucalyptus punctata",
      "Eucalyptus purpurata",
      "Eucalyptus pyrenea",
      "Eucalyptus pyriformis",
      "Eucalyptus pyrocarpa",
      "Eucalyptus quadrangulata",
      "Eucalyptus quadrans",
      "Eucalyptus quadricostata",
      "Eucalyptus quaerenda",
      "Eucalyptus quinniorum",
      "Eucalyptus racemosa",
      "Eucalyptus radiata",
      "Eucalyptus radiata subsp. robertsonii",
      "Eucalyptus radiata subsp. sejuncta",
      "Eucalyptus rameliana",
      "Eucalyptus raveretiana",
      "Eucalyptus ravida",
      "Eucalyptus recta",
      "Eucalyptus recurva",
      "Eucalyptus redimiculifera",
      "Eucalyptus redunca",
      "Eucalyptus regnans",
      "Eucalyptus relicta",
      "Eucalyptus remota",
      "Eucalyptus repullulans",
      "Eucalyptus resinifera",
      "Eucalyptus resinifera subsp. hemilampra",
      "Eucalyptus retinens",
      "Eucalyptus retusa",
      "Eucalyptus rhodantha",
      "Eucalyptus rhodantha var. petiolaris",
      "Eucalyptus rhombica",
      "Eucalyptus rhomboidea",
      "Eucalyptus rigens",
      "Eucalyptus rigidula",
      "Eucalyptus risdonii",
      "Eucalyptus robusta",
      "Eucalyptus rodwayi",
      "Eucalyptus rosacea",
      "Eucalyptus rossii",
      "Eucalyptus rowleyi",
      "Eucalyptus roycei",
      "Eucalyptus rubida",
      "Eucalyptus rubida subsp. barbigerorum",
      "Eucalyptus rubiginosa",
      "Eucalyptus rudderi",
      "Eucalyptus rudis",
      "Eucalyptus rudis subsp. cratyantha",
      "Eucalyptus rugosa",
      "Eucalyptus rugulata",
      "Eucalyptus rummeryi",
      "Eucalyptus rupestris",
      "Eucalyptus sabulosa",
      "Eucalyptus salicola",
      "Eucalyptus saligna",
      "Eucalyptus salmonophloia",
      "Eucalyptus salubris",
      "Eucalyptus sargentii",
      "Eucalyptus sargentii subsp. onesia",
      "Eucalyptus sargentii subsp. sargentii",
      "Eucalyptus saxatilis",
      "Eucalyptus scias",
      "Eucalyptus scias subsp. apoda",
      "Eucalyptus scias subsp. scias",
      "Eucalyptus scoparia",
      "Eucalyptus scopulorum",
      "Eucalyptus scyphocalyx",
      "Eucalyptus scyphocalyx subsp. scyphocalyx",
      "Eucalyptus scyphocalyx subsp. triadica",
      "Eucalyptus seeana",
      "Eucalyptus semiglobosa",
      "Eucalyptus semota",
      "Eucalyptus sepulcralis",
      "Eucalyptus serraensis",
      "Eucalyptus sessilis",
      "Eucalyptus sheathiana",
      "Eucalyptus shirleyi",
      "Eucalyptus sicilifolia",
      "Eucalyptus siderophloia",
      "Eucalyptus sideroxylon",
      "Eucalyptus sideroxylon subsp. improcera",
      "Eucalyptus sideroxylon subsp. sideroxylon",
      "Eucalyptus sieberi",
      "Eucalyptus silvestris",
      "Eucalyptus similis",
      "Eucalyptus singularis",
      "Eucalyptus sinuosa",
      "Eucalyptus smithii",
      "Eucalyptus socialis",
      "Eucalyptus socialis subsp. eucentrica",
      "Eucalyptus socialis subsp. victoriensis",
      "Eucalyptus socialis subsp. viridans",
      "Eucalyptus sparsa",
      "Eucalyptus sparsifolia",
      "Eucalyptus spathulata",
      "Eucalyptus spathulata subsp. salina",
      "Eucalyptus spathulata subsp. spathulata",
      "Eucalyptus sphaerocarpa",
      "Eucalyptus splendens",
      "Eucalyptus sporadica",
      "Eucalyptus spreta",
      "Eucalyptus squamosa",
      "Eucalyptus staeri",
      "Eucalyptus staigeriana",
      "Eucalyptus steedmanii",
      "Eucalyptus stellulata",
      "Eucalyptus stenostoma",
      "Eucalyptus stoatei",
      "Eucalyptus stowardii",
      "Eucalyptus striaticalyx",
      "Eucalyptus striaticalyx subsp. delicata",
      "Eucalyptus stricklandii",
      "Eucalyptus stricta",
      "Eucalyptus strzeleckii",
      "Eucalyptus sturgissiana",
      "Eucalyptus subangusta",
      "Eucalyptus subangusta subsp. cerina",
      "Eucalyptus subangusta subsp. pusilla",
      "Eucalyptus subangusta subsp. subangusta",
      "Eucalyptus subangusta subsp. virescens",
      "Eucalyptus subcrenulata",
      "Eucalyptus suberea",
      "Eucalyptus subtilis",
      "Eucalyptus suffulgens",
      "Eucalyptus suggrandis",
      "Eucalyptus suggrandis subsp. promiscua",
      "Eucalyptus suggrandis subsp. suggrandis",
      "Eucalyptus surgens",
      "Eucalyptus sweedmaniana",
      "Eucalyptus synandra",
      "Eucalyptus talyuberlup",
      "Eucalyptus tardecidens",
      "Eucalyptus taurina",
      "Eucalyptus tectifica",
      "Eucalyptus tenella",
      "Eucalyptus tenera",
      "Eucalyptus tenuipes",
      "Eucalyptus tenuiramis",
      "Eucalyptus tenuis",
      "Eucalyptus tephroclada",
      "Eucalyptus tephrodes",
      "Eucalyptus terebra",
      "Eucalyptus tereticornis",
      "Eucalyptus tereticornis subsp. basaltica",
      "Eucalyptus tereticornis subsp. mediana",
      "Eucalyptus tereticornis subsp. rotunda",
      "Eucalyptus terrica",
      "Eucalyptus tetrapleura",
      "Eucalyptus tetraptera",
      "Eucalyptus tetrodonta",
      "Eucalyptus thamnoides",
      "Eucalyptus thamnoides subsp. megista",
      "Eucalyptus thamnoides subsp. thamnoides",
      "Eucalyptus tholiformis",
      "Eucalyptus thozetiana",
      "Eucalyptus tindaliae",
      "Eucalyptus tintinnans",
      "Eucalyptus todtiana",
      "Eucalyptus torquata",
      "Eucalyptus tortilis",
      "Eucalyptus transcontinentalis",
      "Eucalyptus tricarpa",
      "Eucalyptus tricarpa subsp. decora",
      "Eucalyptus triflora",
      "Eucalyptus trivalva",
      "Eucalyptus tumida",
      "Eucalyptus ultima",
      "Eucalyptus umbra",
      "Eucalyptus umbrawarrensis",
      "Eucalyptus uncinata",
      "Eucalyptus urna",
      "Eucalyptus urnigera",
      "Eucalyptus urophylla",
      "Eucalyptus utilis",
      "Eucalyptus valens",
      "Eucalyptus varia",
      "Eucalyptus varia subsp. salsuginosa",
      "Eucalyptus vegrandis",
      "Eucalyptus vegrandis subsp. recondita",
      "Eucalyptus vernicosa",
      "Eucalyptus verrucata",
      "Eucalyptus vesiculosa",
      "Eucalyptus vicina",
      "Eucalyptus victoriana",
      "Eucalyptus victrix",
      "Eucalyptus viminalis",
      "Eucalyptus viminalis subsp. cygnetensis",
      "Eucalyptus viminalis subsp. hentyensis",
      "Eucalyptus viminalis subsp. pryoriana",
      "Eucalyptus viminalis subsp. siliceana",
      "Eucalyptus virens",
      "Eucalyptus virginea",
      "Eucalyptus viridis",
      "Eucalyptus vittata",
      "Eucalyptus vokesensis",
      "Eucalyptus volcanica",
      "Eucalyptus walshii",
      "Eucalyptus wandoo",
      "Eucalyptus wandoo subsp. pulverea",
      "Eucalyptus websteriana",
      "Eucalyptus websteriana subsp. norsemanica",
      "Eucalyptus wetarensis",
      "Eucalyptus whitei",
      "Eucalyptus wilcoxii",
      "Eucalyptus williamsiana",
      "Eucalyptus willisii",
      "Eucalyptus wimmerensis",
      "Eucalyptus woodwardii",
      "Eucalyptus woollsiana",
      "Eucalyptus wubinensis",
      "Eucalyptus wyolensis",
      "Eucalyptus xanthonema",
      "Eucalyptus xanthonema subsp. apposita",
      "Eucalyptus xerothermica",
      "Eucalyptus yalatensis",
      "Eucalyptus yarraensis",
      "Eucalyptus yarriambiack",
      "Eucalyptus yilgarnensis",
      "Eucalyptus youmanii",
      "Eucalyptus youmanii var. sphaerocarpa",
      "Eucalyptus youngiana",
      "Eucalyptus yumbarrana",
      "Eucalyptus zopherophloia",
    ];
    it("in sorted order", () => {
      const items: [string, number][] = [];
      for (let i = 0; i < names.length; ++i) {
        items.push([names[i], i]);
      }
      const T: RBTree<number> = new RBTree<number>();
      const U = T.insertMany(items);
      for (let i = 0; i < names.length; ++i) {
        const r = U.find(names[i]);
        expect(r).is.not.undefined;
        expect(r).to.eql(i);
      }
    });
    it("in random order", () => {
      const items: [string, number][] = [];
      for (let i = 0; i < names.length; ++i) {
        items.push([names[i], i]);
      }
      const n = items.length;
      for (let i = 0; i < items.length; ++i) {
        const j = Math.floor(n * Math.random());
        if (j != i) {
          const t = items[i];
          items[i] = items[j];
          items[j] = t;
        }
      }
      const T: RBTree<number> = new RBTree<number>();
      const U = T.insertMany(items);
      for (let i = 0; i < names.length; ++i) {
        const r = U.find(names[i]);
        expect(r).is.not.undefined;
        expect(r).to.eql(i);
      }
    });
  });
});
